export default [
  {
    img: require('../img/h5.jpg'),
    roomname: 'Nombre Habitación',
    numberbeds: '# camas',
    numberbath: '# baños',
    numberbalc: '# balcones',
    numberhuespe: '# huespedes',
    specialdetails: 'Detalles Especiales',
    price: '$ 00.00/día',
  },
  {
    img: require('../img/h3.jpg'),
    roomname: 'Nombre Habitación',
    numberbeds: '# camas',
    numberbath: '# baños',
    numberbalc: '# balcones',
    numberhuespe: '# huespedes',
    specialdetails: 'Detalles Especiales',
    price: '$ 00.00/día',
  },
  {
    img: require('../img/h2.jpg'),
    roomname: 'Nombre Habitación',
    numberbeds: '# camas',
    numberbath: '# baños',
    numberbalc: '# balcones',
    numberhuespe: '# huespedes',
    specialdetails: 'Detalles Especiales',
    price: '$ 00.00/día',
  },
  {
    img: require('../img/h1.jpg'),
    roomname: 'Nombre Habitación',
    numberbeds: '# camas',
    numberbath: '# baños',
    numberbalc: '# balcones',
    numberhuespe: '# huespedes',
    specialdetails: 'Detalles Especiales',
    price: '$ 00.00/día',
  },
  {
    img: require('../img/h4.jpg'),
    roomname: 'Nombre Habitación',
    numberbeds: '# camas',
    numberbath: '# baños',
    numberbalc: '# balcones',
    numberhuespe: '# huespedes',
    specialdetails: 'Detalles Especiales',
    price: '$ 00.00/día',
  },
];
